Repository feLlx/JavaProject-DauphineM1-2019, pull requests merged in 2020-02, with the labels that each got.

#2 Build project
  .classpath
  .gitignore
  .project
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.m2e.core.prefs
  .travis.yml
  pom.xml
  src/main/java/io/github/JavaProject_DauphineM1_2019/App.java
  src/main/resources/logback.xml
  src/test/java/io/github/JavaProject_DauphineM1_2019/log/LogTest.java
  src/test/resources/Temp
Labels: documentation, enhancement

#1 roadMap and project description
  README.md
Labels: documentation

#4 Read json
  .classpath
  .gitignore
  .metadata/.lock
  .metadata/.log
  .metadata/.mylyn/.taskListIndex/segments.gen
  .metadata/.mylyn/.taskListIndex/segments_1
  .metadata/.mylyn/repositories.xml.zip
  .metadata/.mylyn/tasks.xml.zip
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/history.version
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.index
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.version
  .metadata/.plugins/org.eclipse.core.resources/.root/1.tree
  .metadata/.plugins/org.eclipse.core.resources/.safetable/org.eclipse.core.resources
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.core.resources.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.epp.logging.aeri.ide.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.ui.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.discovery.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.mylyn.context.core.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.mylyn.monitor.ui.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.mylyn.tasks.ui.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.team.ui.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.ide.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.workbench.prefs
  .metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
  .metadata/.plugins/org.eclipse.jdt.core/assumedExternalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/externalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/nonChainingJarsCache
  .metadata/.plugins/org.eclipse.jdt.core/variablesAndContainers.dat
  .metadata/.plugins/org.eclipse.jdt.ui/OpenTypeHistory.xml
  .metadata/.plugins/org.eclipse.jdt.ui/QualifiedTypeNameHistory.xml
  .metadata/.plugins/org.eclipse.jdt.ui/dialog_settings.xml
  .metadata/.plugins/org.eclipse.m2e.logback.configuration/0.log
  .metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.7.0.20160603-1933.xml
  .metadata/.plugins/org.eclipse.oomph.setup/workspace.setup
  .metadata/.plugins/org.eclipse.ui.intro/introstate
  .metadata/.plugins/org.eclipse.ui.workbench/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml
  .metadata/version.ini
  .project
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.m2e.core.prefs
  .travis.yml
  pom.xml
  src/main/java/io/github/JavaProject_DauphineM1_2019/App.java
  src/main/java/io/github/JavaProject_DauphineM1_2019/json/ReadJson.java
  src/main/resources/AnonymisationRules.json
  src/main/resources/ObjectsDescription.json
  src/main/resources/VerificationRules.json
  src/main/resources/logback.xml
  src/test/java/io/github/JavaProject_DauphineM1_2019/json/ReadJsonTest.java
  src/test/java/io/github/JavaProject_DauphineM1_2019/log/LogTest.java
  src/test/resources/Temp
Labels: enhancement

#6 Read json
  .metadata/.lock
  .metadata/.log
  .metadata/.mylyn/.taskListIndex/segments.gen
  .metadata/.mylyn/.taskListIndex/segments_1
  .metadata/.mylyn/repositories.xml.zip
  .metadata/.mylyn/tasks.xml.zip
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/history.version
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.index
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.version
  .metadata/.plugins/org.eclipse.core.resources/.root/1.tree
  .metadata/.plugins/org.eclipse.core.resources/.safetable/org.eclipse.core.resources
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.core.resources.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.epp.logging.aeri.ide.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.ui.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.discovery.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.mylyn.context.core.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.mylyn.monitor.ui.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.mylyn.tasks.ui.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.team.ui.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.ide.prefs
  .metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.workbench.prefs
  .metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
  .metadata/.plugins/org.eclipse.jdt.core/assumedExternalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/externalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/nonChainingJarsCache
  .metadata/.plugins/org.eclipse.jdt.core/variablesAndContainers.dat
  .metadata/.plugins/org.eclipse.jdt.ui/OpenTypeHistory.xml
  .metadata/.plugins/org.eclipse.jdt.ui/QualifiedTypeNameHistory.xml
  .metadata/.plugins/org.eclipse.jdt.ui/dialog_settings.xml
  .metadata/.plugins/org.eclipse.m2e.logback.configuration/0.log
  .metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.7.0.20160603-1933.xml
  .metadata/.plugins/org.eclipse.oomph.setup/workspace.setup
  .metadata/.plugins/org.eclipse.ui.intro/introstate
  .metadata/.plugins/org.eclipse.ui.workbench/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml
  .metadata/version.ini
  pom.xml
  src/main/java/io/github/JavaProject_DauphineM1_2019/json/ReadJson.java
  src/main/resources/AnonymisationRules.json
  src/main/resources/ObjectsDescription.json
  src/main/resources/VerificationRules.json
  src/test/java/io/github/JavaProject_DauphineM1_2019/json/ReadJsonTest.java
Labels: duplicate, enhancement
